### ISSUE TITLE
UDフォントの導入

### ISSUE THREAD

**Issue by nagataniyoshiki** [1heisuzuki/speech-to-text-webcam-overlay#23]
名称は
font-family:"BIZ UDGothic";
です。よろしくお願いします。
（プルリクを送るほどでは無いものの Twitter だけだと忘れるので Issue で失礼します。）

**Comment by 1heisuzuki** [comment]
ありがとうございます！追って確認します。 @nagataniyoshiki

**Comment by 1heisuzuki** [comment]
BIZ UD ゴシックはWebフォントとして利用できないようです。
https://support.bizplus.typesquare.com/hc/ja/articles/360004820071-Webフォントとして利用可能ですか-

「みんなの文字」はWeb用のものが公開されていますが，ちょっとライセンス周り（埋め込み用のコードが申請ベースで発行されるため）確認してみます。
https://minmoji.ucda.jp/pages/webfont/

**Comment by 1heisuzuki** [comment]
「みんなの文字」Webフォントの管理団体にメールで問い合わせを行いました。
https://minmoji.ucda.jp/pages/webfont/

状況：
- サイトのソースコードをオープンソースとして公開しているため，他のユーザーが派生のサイトを作成する可能性がある
- その際， @1heisuzuki が申請・発行した「みんなの文字」WebフォントのタグURLがそのまま流用されてしまう可能性がある
 
質問：
1.  固有タグによって， 1heisuzuki.github.io/speech-to-text-webcam-overlay 以外のWebページに設置された場合，みんなの文字Webフォントが配信がされない設定になっているのか
1.  そのの設定の有無関わらず，今回のような状況でみんなの文字Webフォントを利用することは可能か

**Comment by 1heisuzuki** [comment]
BIZ UD ゴシックは Windowsに搭載されていたので追加します！
https://forest.watch.impress.co.jp/docs/news/1149745.html

**Comment by 1heisuzuki** [comment]
BIZ UDPゴシック／BIZ UDP明朝が，Google Fonts で配信開始されたため対応しました。
Windows10以外の環境でもUDフォントが使えるようになったため，Issueをクローズします。
d8b5316ea6026f0af6d010a9dee7f97cc6848a10

参考：https://www.morisawa.co.jp/about/news/6706
