### ISSUE TITLE
日本語以外の選択肢があったら

### ISSUE THREAD

**Issue by shilik** [1heisuzuki/speech-to-text-webcam-overlay#24]
@1heisuzuki 
素晴らしいシステムを開発していただき、ありがとうございます。
もし、音声認識には日本語以外の選択肢があったら、語学的な口頭練習にも役に立っているのではないかと思いますが、この機能を開発なさるご予定がございますか。

**Comment by 1heisuzuki** [comment]
@shilik コメントありがとうございます！

多言語の実装は対応済みです。画面下部より，入力言語および表示言語（翻訳）の設定が可能です。ご確認のほどよろしくお願いいたします。

<img width="1037" alt="SS 2020-05-23 at 23 44 34" src="https://user-images.githubusercontent.com/14171207/82800054-fe3e8200-9eb5-11ea-8b1f-5b4fa28eb2a0.png">
