### ISSUE TITLE
【修正依頼】インカメの映像が左右反転してる？

### ISSUE THREAD

**Issue by y4f** [1heisuzuki/speech-to-text-webcam-overlay#31]
右に動くと画面上では左に動きます。修正お願いします。

**Comment by 1heisuzuki** [comment]
@y4f ありがとうございます！

文字と相手側からの見た目が反転しないように，文字・映像とも順表示していましたが，それぞれ左右反転できるオプションを追加してみます。

すぐには対応難しいかもしれませんが，気長にお待ちいただけましたら幸いです🙏

**Comment by 1heisuzuki** [comment]
機能追加しました！ @y4f 

- 文字と映像それぞれの反転ボタンを追加
- 文字の非表示ボタンを追加
- デフォルトはNot左右反転 → 相手への映像も反転してしまうため，カメラで文字等を映す際問題になるため

**Comment by y4f** [comment]
ありがとうございます。
