### ISSUE TITLE
動作環境の追記依頼

### ISSUE THREAD

**Issue by sksthrs** [1heisuzuki/speech-to-text-webcam-overlay#41]
次の環境でも動作しました。

- Windows 10のVivaldi（https://vivaldi.com/ja/）
- Linux (Ubuntu Mate 20.04)上のChrome、Chromium、Vivaldi

ChromiumベースのEdgeは、さすがに（Googleに依存する）Speech Recognition APIが動きませんね。

**Comment by 1heisuzuki** [comment]
確認ありがとうございます！

- Windows 10 の Chromium 
- macOS の Chromium，Vivaldi
においても確認できたので，あわせて追記しておきました。 9b0bc6c8fb7b7967e41769bd1cc160a2c8448f54

**Comment by 1heisuzuki** [comment]
EdgeもWeb Speech API 自体は対応しているみたいなんですが，うまく動かないみたいですね…
https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API

**Comment by sksthrs** [comment]
追記ありがとうございました。

Chromium Edge、私も試したんですが、動きませんでした。やはりGoogleに依存している部分は何か改変されているのでしょうね。
