### ISSUE TITLE
文字に輪郭を付ける

### ISSUE THREAD

**Issue by nagataniyoshiki** [1heisuzuki/speech-to-text-webcam-overlay#8]
こちらでちょっと試してみたところ，少し文字の輪郭を付けると背景に影響されることが減る気がしました。もしよろしければお試しください（評価実験等の成果を反映した設定なのでしたら捨て置き下さい）。
-webkit-text-stroke: 1px #000;

**Comment by 1heisuzuki** [comment]
ありがとうございます！

少し調整の上，反映しました：
- デフォルトは少し細め（見た目の良さとのバランス）
- スライダーで調整可能に
2159d73abad9f3b03a907c32c7f7f9dce42ccfbc
